# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main", "devel" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [ '17', '20' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.Java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.Java }}
        distribution: 'temurin'
        cache: 'gradle'
    - run: '(cd jproto && ./gradlew --no-daemon --profile clean test build run installDist'
    - run: '(cd jproto && build/install/jproto/bin/jproto)'
    
#    - name: Build with Gradle
#      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#      with:
#        arguments: build
